#!/usr/bin/env bash
#pkill
echo "$$" >> /var/run/myscript.pid
cleanup() {
  echo "Deleting PID file..."
  rm -f "/var/run/myscript.pid"
  exit 0
}
echo $$ > "/var/run/myscript.pid"
trap 'echo " Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap 'cleanup' SIGQUIT
echo "To infinity and beyond"
while true
do
  sleep 2
done
